all:
	inkscape -z -e ../back.imageset/back.png -w 24 -h 24 ios-arrow-back.svg
	inkscape -z -e ../back.imageset/back@2x.png -w 48 -h 48 ios-arrow-back.svg
	inkscape -z -e ../back.imageset/back@3x.png -w 72 -h 72 ios-arrow-back.svg

	inkscape -z -e ../forward.imageset/forward.png -w 24 -h 24 ios-arrow-forward.svg
	inkscape -z -e ../forward.imageset/forward@2x.png -w 48 -h 48 ios-arrow-forward.svg
	inkscape -z -e ../forward.imageset/forward@3x.png -w 72 -h 72 ios-arrow-forward.svg

	inkscape -z -e ../refresh.imageset/refresh.png -w 24 -h 24 ios-refresh-empty.svg
	inkscape -z -e ../refresh.imageset/refresh@2x.png -w 48 -h 48 ios-refresh-empty.svg
	inkscape -z -e ../refresh.imageset/refresh@3x.png -w 72 -h 72 ios-refresh-empty.svg
