# Use the CDN to make CircleCI builds faster.
source 'https://cdn.cocoapods.org/'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'FontScreenshotter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FontScreenshotter
  pod 'Protobuf', '~> 3.12.0'

  target 'FontScreenshotterUITests' do
    # Pods for testing
  end

end

target 'Tsurukame' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tsurukame
  pod 'Protobuf', '~> 3.12.0'

  target 'Tests' do
    inherit! :search_paths
  end
end
