# Use the CDN to make CircleCI builds faster.
source 'https://cdn.cocoapods.org/'

platform :ios, '12.0'

target 'FontScreenshotter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FontScreenshotter
  pod 'Haneke', '~> 1.0.2', :inhibit_warnings => true
  pod 'Reachability', '~> 3.2'

  target 'FontScreenshotterUITests' do
    # Pods for testing
  end

end

target 'Tsurukame' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tsurukame
  pod 'FMDB', '~> 2.7.5'
  pod 'Haneke', '~> 1.0.2', :inhibit_warnings => true
  pod 'MMDrawerController', '~> 0.6.0', :inhibit_warnings => true
  pod 'Reachability', '~> 3.2'
  pod 'SwiftGen', '~> 6.0'

  target 'Tests' do
    inherit! :search_paths

    platform :ios, '12.0'
    pod 'Hippolyte', '~> 1.3.0'
  end
end

# Delete the IPHONEOS_DEPLOYMENT_TARGET config setting so it inherits the
# podfile platform setting.
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings['ENABLE_BITCODE'] = 'YES'
    end
  end
end