# Use the CDN to make CircleCI builds faster.
source 'https://cdn.cocoapods.org/'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'FontScreenshotter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FontScreenshotter
  pod 'Haneke', '~> 1.0.2', :inhibit_warnings => true
  pod 'Protobuf', '~> 3.13.0'
  pod 'Reachability', '~> 3.2'

  target 'FontScreenshotterUITests' do
    # Pods for testing
  end

end

target 'Tsurukame' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tsurukame
  pod 'Charts', '~> 3.5.0', :inhibit_warnings => true
  pod 'FMDB', '~> 2.7.5'
  pod 'Haneke', '~> 1.0.2', :inhibit_warnings => true
  pod 'Light-Untar', '~> 0.3.0', :inhibit_warnings => true
  pod 'MMDrawerController', '~> 0.6.0', :inhibit_warnings => true
  pod 'Protobuf', '~> 3.13.0'
  pod 'Reachability', '~> 3.2'

  target 'Tests' do
    inherit! :search_paths
  end
end
