# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do
  setup_circle_ci
end

lane :test do
  run_tests(scheme: "Tsurukame")
end

lane :release do
  match(type: "appstore")
  increment_version_number(
    bump_type: "minor",
    xcodeproj: "Tsurukame.xcodeproj"
  )
  build_app(
    scheme: "Tsurukame",
    include_bitcode: true,
  )
  upload_to_app_store(
    app_icon: "Resources/Assets.xcassets/svg/appicon.png",
    changelog: prompt(
      text: "Changelog: ",
      multi_line_end_keyword: "END"
    ),
  )
  commit_version_bump(xcodeproj: "Tsurukame.xcodeproj")
  add_git_tag(tag: lane_context[SharedValues::VERSION_NUMBER])
  push_to_git_remote
end
